apiVersion: v1
kind: Service
metadata:
  name: sitas-frontend
  namespace: sitas
  labels:
    app: sitas-frontend
spec:
  type: LoadBalancer
  selector:
    app: sitas-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31000