apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitas-frontend
  namespace: sitas
spec:
  selector:
    matchLabels:
      app: sitas-frontend
  template:
    metadata:
      labels:
        app: sitas-frontend
    spec:
      containers:
        - name: sitas-frontend
          image: oscarvicente/sitas-frontend
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
              cpu: "2"
          ports:
            - name: http
              protocol: TCP
              containerPort: 80